# PyTorch and NumPy Basics

In [2]:
import numpy as np
import torch

In [4]:
# Creating a 2x2 array
arr = [[1,2],[3,4]]
arr

[[1, 2], [3, 4]]

In [8]:
# Convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [10]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [12]:
# Create matrices with default values
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [17]:
np.random.rand(2,2)

array([[0.07903026, 0.44167345],
       [0.07407092, 0.44849586]])

In [19]:
torch.rand((2,2))

tensor([[0.8546, 0.0718],
        [0.8702, 0.8740]])

# Seeds for Reproducibility 

In [23]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [25]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [27]:
np.random.rand(2,2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [29]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [33]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

# NumPy to PyTorch

In [35]:
# Numpy Array
np_array = np.ones((2,2))

In [37]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [39]:
# Convert to torch tensor
torch_tensor = torch.from_numpy(np_array)

In [41]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


# Torch to NumPy

In [49]:
torch_tensor = torch.ones(2,2)

In [50]:
type(torch_tensor)

torch.Tensor

In [47]:
torch_to_numpy = torch_tensor.numpy()

In [51]:
type(torch_to_numpy)

numpy.ndarray

# Resize Tensor 

In [58]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [60]:
print(a.size())

torch.Size([2, 2])


In [63]:
a.view(4)

tensor([1., 1., 1., 1.])

# Element wise Addition

In [65]:
a = torch.ones(2,2)

In [66]:
b = torch.ones(2,2)

In [68]:
c = a + b

In [70]:
c

tensor([[2., 2.],
        [2., 2.]])

In [72]:
c.add_(a)

tensor([[4., 4.],
        [4., 4.]])

In [74]:
d = a - b

In [76]:
d

tensor([[0., 0.],
        [0., 0.]])

In [78]:
a.sub_(b)

tensor([[-1., -1.],
        [-1., -1.]])

# Element wise multiplication

In [79]:
a = torch.ones(2,2)

In [80]:
b = torch.zeros(2,2)

In [82]:
c = a * b

In [84]:
c

tensor([[0., 0.],
        [0., 0.]])

In [87]:
print(a.mul_(b))
a

tensor([[0., 0.],
        [0., 0.]])


tensor([[0., 0.],
        [0., 0.]])

# Element wise divison

In [88]:
a = torch.ones(2,2)

In [89]:
b = torch.zeros(2,2)

In [91]:
b/a

tensor([[0., 0.],
        [0., 0.]])

In [94]:
print(b.div(a))

tensor([[0., 0.],
        [0., 0.]])


In [96]:
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

# Tensor Mean

In [101]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [104]:
a.mean(dim=0)

tensor(5.5000)

In [107]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [111]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

# Tensor Standard Deviation

In [113]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)

# Variables & Gradients in PyTorch

In [114]:
import torch
from torch.autograd import Variable

In [118]:
a = Variable(torch.ones(2,2),requires_grad=True)

In [120]:
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [122]:
a = torch.ones(2,2)