In [2]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00],
        [8.5899e+09, 1.4013e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1824, 0.8414, 0.2149],
        [0.3509, 0.5795, 0.6617],
        [0.2938, 0.6658, 0.4702],
        [0.4058, 0.5031, 0.1116],
        [0.9445, 0.8999, 0.5207]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2882, -1.1142, -0.2769],
        [-0.5520,  3.2112, -1.0735],
        [-0.1645, -0.1341,  0.2152],
        [-0.2361, -0.7720, -0.3075],
        [ 0.1439, -0.9866,  0.4337]])


In [14]:
print(x.size())

torch.Size([5, 3])


In [17]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.2882, -1.1142, -0.2769],
        [-0.5520,  3.2112, -1.0735],
        [-0.1645, -0.1341,  0.2152],
        [-0.2361, -0.7720, -0.3075],
        [ 0.1439, -0.9866,  0.4337]])
tensor([[0.2541, 0.7893, 0.1450],
        [0.9536, 0.9640, 0.7437],
        [0.9340, 0.3531, 0.8109],
        [0.4732, 0.7469, 0.7639],
        [0.8673, 0.8436, 0.6536]])
tensor([[ 0.5423, -0.3250, -0.1319],
        [ 0.4016,  4.1752, -0.3298],
        [ 0.7695,  0.2189,  1.0261],
        [ 0.2371, -0.0251,  0.4563],
        [ 1.0112, -0.1430,  1.0873]])


In [19]:
print(torch.add(x, y))

tensor([[ 0.5423, -0.3250, -0.1319],
        [ 0.4016,  4.1752, -0.3298],
        [ 0.7695,  0.2189,  1.0261],
        [ 0.2371, -0.0251,  0.4563],
        [ 1.0112, -0.1430,  1.0873]])


In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5423, -0.3250, -0.1319],
        [ 0.4016,  4.1752, -0.3298],
        [ 0.7695,  0.2189,  1.0261],
        [ 0.2371, -0.0251,  0.4563],
        [ 1.0112, -0.1430,  1.0873]])


In [23]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 8.3055e-01, -1.4392e+00, -4.0883e-01],
        [-1.5041e-01,  7.3864e+00, -1.4033e+00],
        [ 6.0493e-01,  8.4809e-02,  1.2412e+00],
        [ 9.7299e-04, -7.9715e-01,  1.4877e-01],
        [ 1.1552e+00, -1.1296e+00,  1.5209e+00]])


In [25]:
print(x[:, 1])

tensor([-1.1142,  3.2112, -0.1341, -0.7720, -0.9866])


In [27]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.6676])
0.6675862669944763


In [31]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [33]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)
print(a)
print(b)


tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
